server:
  port: 8080
spring:
  data:
    mongodb:
      database: merchants
      uri: mongodb+srv://gabriel:G15abriel@cluster0.htcjwxb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-38ii0jjjgq7oenfs.us.auth0.com/
okta:
  oauth2:
    audience: http://localhost:8081/
    issuer: https://dev-38ii0jjjgq7oenfs.us.auth0.com/

logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: DEBUG