name: Deploy to GCP

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:

      # Git checkout
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIAL_UPDATED }}
          install_components: 'gke-gcloud-auth-plugin'
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/tensile-courier-421213/test/nginx:latest .
          docker push us-central1-docker.pkg.dev/tensile-courier-421213/test/nginx:latest
