name: Deploy to GCP

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - uses: thecodemonkey/action-get-gradle-version@master     # <- USE THIS ACTION TO READ THE VERSION FROM BUILD.GRADLE
        id: version                                              # <- give this step an id to access the output of the step
      - run: 'echo version ${{ steps.version.outputs.version }}'

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v0.4.0
        with:
          token_format: "access_token"
          create_credentials_file: true
          activate_credentials_file: true
          workload_identity_provider: 'projects/90412647156/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
          service_account: 'test-wif@tensile-courier-421213.iam.gserviceaccount.com'
          access_token_lifetime: '100s'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - name: Set credential_file
        run: gcloud auth login --cred-file=${{steps.auth.outputs.credentials_file_path}}

#      - name: Run gcloud
#        run: gcloud compute instances list --zones us-central1-a

#      - id: gclouds
#        name: Repository Creation
#        run: |-
#          gcloud artifacts repositories create user-service --repository-format=docker --location=us-central1 --description="Application repository" --immutable-tags --async

      - id: gcloud
        name: Deploy to Artifact Registry
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker build -t us-central1-docker.pkg.dev/tensile-courier-421213/user-service/user-service .
          docker push us-central1-docker.pkg.dev/tensile-courier-421213/user-service/user-service
