name: Deploy to GCP

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write

jobs:
  deploy:
    name: Setup Gcloud Account
    runs-on: ubuntu-latest
    steps:

      # Git checkout
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew clean build

      - id: 'auth'
        name: 'Authenticate to GCP'
        uses: 'google-github-actions/auth@v0.3.1'
        with:
          create_credentials_file: 'true'
          workload_identity_provider: '/projects/90412647156/locations/global/workloadIdentityPools/github/providers/github-github'
          service_account: 'cicd-999@tensile-courier-421213.iam.gserviceaccount.com'

      - id: 'gcloud'
        name: 'gcloud'
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
          docker build -t us-central1-docker.pkg.dev/tensile-courier-421213/test/nginx:latest .
          docker push us-central1-docker.pkg.dev/tensile-courier-421213/test/nginx:latest

      # - name: Configure Docker Client
      #   run: |-
      #     gcloud auth configure-docker --quiet

      #- name: build and push the docker image
      #  env:
      #    GOOGLE_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      #  run: |
      #    gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
      #    docker build -t us-central1-docker.pkg.dev/tensile-courier-421213/test/nginx:latest .
      #    docker push us-central1-docker.pkg.dev/tensile-courier-421213/test/nginx:latest
